var globalModelsDetails = {
"cayman": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 345,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Porsche Cayman"
    },
"bmwg20": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 345,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW G20"
    },
"gcmlc300": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 345,
        priv: "Задний привод",
        mass: "2.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Land Cruiser 300"
    },
"subisti08": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 345,
        priv: "Задний привод",
        mass: "1.230 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Subaru Impreza WRX STi"
    },
"a80": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 345,
        priv: "Задний привод",
        mass: "2.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Supra A80"
    },
"c63scoupe": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 345,
        priv: "Задний привод",
        mass: "2.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz C63S Coupe"
    },
"terzo": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 345,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Terzo Millennio"
    },
"divo": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 445,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Bugatti Divo"
    },
"jzx100": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 245,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Chaser JZX100"
    },
"urus": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Urus"
    },
"amggt16": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz AMG GT"
    },
"c63": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz C63 AMG"
    },
"ninjah2r": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 425,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Kawasaki Ninja H2R"
    },
"avtr": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 385,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz VISION AVTR"
    },
"bc": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Pagani Huayra BC"
    },
"cbr17": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Honda CBR 17"
    },
"gsx1000": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Suzuki GSX-R 1000"
    },
"mbslr": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz SLR McLaren"
    },
    "pullman": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 345,
        priv: "Задний привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz Pullman"
    },
	"w223": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 335,
        priv: "Полный привод",
        mass: "1.480 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz W223"
    },
	"e63sf": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 120,
        priv: "Задний привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz E63S 2020"
    },
	"impala": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "2.625 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Chevrolet Impala"
    },
	"lincoln": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 328,
        priv: "Задний привод",
        mass: "1.356 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lincoln"
    },
	"subarusti8": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 326,
        priv: "Задний привод",
        mass: "1.368 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Subaru STI"
    },
	"subaru": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 285,
        priv: "Задний привод",
        mass: "1.385 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Subaru STI 2018"
    },
	"camryv55": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 330,
        priv: "Полный привод",
        mass: "1.600 кг.",
        vnet: "Нет", 
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Camry V55"
    },
	"tsgr20": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 345,
        priv: "Полный привод",
        mass: "1.750 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Supra 2020"
    },
	"e63s": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 420,
        priv: "Задний привод",
        mass: "1.395 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz E63S 2019"
    },
	"vesta": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 318,
        priv: "Задний привод",
        mass: "1.650 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lada Vesta"
    },
	"lc500": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Передний привод",
        mass: "1.163 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lexus LC500"
    },
	"continental": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 306,
        priv: "Полный привод",
        mass: "2.491 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Bentley Continental"
    },
	"g65": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "1.930 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz G65 AMG"
    },
	"gtrr50": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 280,
        priv: "Задний привод",
        mass: "1.550 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Nissan GTR-R 50"
    },
	"svr": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 333,
        priv: "Полный привод",
        mass: "2.244 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Range Rover SVR"
    },
	"rrwraith": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Полный привод",
        mass: "3.700 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Rolls-Royce Wraith"
    },
	"m3f80": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 380,
        priv: "Полный привод",
        mass: "1.975 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M3 F80"
    },
	"z4vp": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 306,
        priv: "Задний привод",
        mass: "1.527 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW Z4"
    },
	"w140s600": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 280,
        priv: "Задний привод",
        mass: "1.725 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz S600"
    },
	"w210": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 290,
        priv: "Задний привод",
        mass: "1.680 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz W210"
    },
	"vclass": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 220,
        priv: "Передний привод",
        mass: "1.690 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz V-class"
    },
	"volvo850": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 286,
        priv: "Полный привод",
        mass: "2.175 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Volvo 850"
    },
	"a6": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 420,
        priv: "Полный привод",
        mass: "2.625 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi A6"
    },
	"s63w222": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.660 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz W222 AMG"
    },
	"subwrx": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 335,
        priv: "Задний привод",
        mass: "1.941 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Subaru WRX"
    },
	"msprinter": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.650 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz Sprinter"
    },
	"mp1": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.825 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "McLaren P1"
    },
	"m5comp": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "1.940 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M5 Competition"
    },
	"63gls": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Полный привод",
        mass: "2.800 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz GLS 63"
    },
	"cybertruck": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 230,
        priv: "Полный привод",
        mass: "1.862 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Tesla Cybertruck"
    },
	"vaz2121": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 340,
        priv: "Задний привод",
        mass: "1.435 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Niva Urban"
    },
	"toyotalc200": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Задний привод",
        mass: "1.485 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Land Cruiser 200"
    },
	"teslax": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 312,
        priv: "Задний привод",
        mass: "1.735 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Tesla Model X"
    },
	"sls": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.107 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz SLS"
    },
	"taycan": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 230,
        priv: "Полный привод",
        mass: "2.580 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Porsche Taycan"
    },
	"shelbygt500": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.350 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ford Shelby GT500"
    },
	"s60": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.580 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Volvo S60"
    },
	"rs5audi": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 182,
        priv: "Задний привод",
        mass: "1.577 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi RS5"
    },
	"rs6avant20": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 175,
        priv: "Передний привод",
        mass: "1.160 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi RS6 AVANT"
    },
	"r8v10": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 150,
        priv: "Передний привод",
        mass: "1.060 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi R8 V10"
    },
	"qx80": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 204,
        priv: "Задний привод",
        mass: "1.044 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Infinity QX80"
    },
	"pstgte": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 197,
        priv: "Задний привод",
        mass: "1.250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Volkswagen Passat B8"
    },
	"panamera_st": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 220,
        priv: "Задний привод",
        mass: "1.250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Porsche Panamera ST"
    },
	"octaviavrs": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 225,
        priv: "Полный привод",
        mass: "1.370 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Skoda Octavia VRS"
    },
	"mk2100": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Передний привод",
        mass: "1.495 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Mark 2"
    },
	"mercxclass": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 221,
        priv: "Полный привод",
        mass: "1.253 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz X-class"
    },
	"MGT": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 150,
        priv: "Передний привод",
        mass: "970 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ford Mustang 5.0"
    },
	"m750li": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 272,
        priv: "Передний привод",
        mass: "1.470 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BWM 750 LI"
    },
	"lx470": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "1.960 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lexus LX470"
    },
	"lx2018": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 260,
        priv: "Задний привод",
        mass: "1.250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lexus LX570"
    },
	"m516": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 350,
        priv: "Задний привод",
        mass: "1.255 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M5 F10"
    },
	"lanxvrp": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 242,
        priv: "Полный привод",
        mass: "1.590 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mitsubishi Lancer Evolution 10"
    },
	"kiastinger": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Задний привод",
        mass: "1.540 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "KIA Stinger"
    },
	"lada2107": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 195,
        priv: "Полный привод",
        mass: "2.585 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lada 2107"
    },
	"lancer9": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 240,
        priv: "Задний привод",
        mass: "1.543 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mitsubishi Lancer Evolution 9"
    },
	"ipace": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 270,
        priv: "Задний привод",
        mass: "2.010 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Jaguar I-pace"
    },
	"jeepsrt": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Полный привод",
        mass: "1.340 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Jeep SRT-8"
    },
	"gtr17": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 220,
        priv: "Полный привод",
        mass: "2.585 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Nissan GTR-R 35"
    },
	"hellcat": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.570 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Dodge Hellcat"
    },
	"impala96": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 280,
        priv: "Задний привод",
        mass: "1.570 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Chevrolet Impala 1996"
    },
	"lykan": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.130 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lykan Hypersport"
    },
	"merse63": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 289,
        priv: "Задний привод",
        mass: "1.707 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz E63 AMG"
    },
	"s15": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.656 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Nissan Sliva S15"
    },
	"gt63": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 320,
        priv: "Полный привод",
        mass: "1.650 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz GT63S AMG"
    },
	"huracan": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 190,
        priv: "Передний привод",
        mass: "1.760 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Huracan"
    },
	"gs350": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 350,
        priv: "Задний привод",
        mass: "1.490 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lexus GS350"
    },
	"gle63": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 306,
        priv: "Полный привод",
        mass: "1.995 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz GLE 63 AMG"
    },
	"golfgti": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 232,
        priv: "Передний привод",
        mass: "1.480 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Volkswagen Golf GTI"
    },
	"gaz2410": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 232,
        priv: "Полный привод",
        mass: "2.220 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Gaz-2410"
    },
	"g30": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 331,
        priv: "Полный привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW 530I G30"
    },
	"g63g6x6": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 340,
        priv: "Задний привод",
        mass: "1.520 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz G63 6x6"
    },
	"g65go": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 225,
        priv: "Полный привод",
        mass: "2.710 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz G63 AMG"
    },
	"focus2003": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 280,
        priv: "Полный привод",
        mass: "1.840 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ford Focus 2003"
    },
	"fordraptor": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 305,
        priv: "Полный привод",
        mass: "2.065 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ford Raptor"
    },
		"escalade": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 305,
        priv: "Полный привод",
        mass: "2.075 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Cadillac Escalade"
    },
		"e36rb": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "1.585 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW E36 DRIFT"
    },
		"e39m5": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.550 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M5 E39"
    },
		"cullinan": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 317,
        priv: "Задний привод",
        mass: "1.695 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Rolls-Royce Cullinan"
    },
		"e200": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.345 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz E200"
    },
		"cls17": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 258,
        priv: "Полный привод",
        mass: "2.418 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz CLS AMG"
    },
		"cooperworks": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "1.480 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mini Cooper"
    },
		"camry70": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 240,
        priv: "Передний привод",
        mass: "1.535 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Camry 70"
    },
		"chiron19": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.500 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Bugatti Chiron"
    },
		"bmwg07": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 350,
        priv: "Полный привод",
        mass: "1.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW X7"
    },
		"bmwm8": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 192,
        priv: "Полный привод",
        mass: "2.291 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M8 Competition"
    },
		"bmwx5mc": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 260,
        priv: "Полный привод",
        mass: "2.263 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW X5M Competition"
    },
		"e60": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 260,
        priv: "Полный привод",
        mass: "2.509 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M5 E60"
    },
		"BMW E34": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 140,
        priv: "Полный привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M5 E34"
    },
		"bmwe38": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 137,
        priv: "Полный привод",
        mass: "1.425 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW E38"
    },
		"asvj": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 305,
        priv: "Полный привод",
        mass: "2.200 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini SVJ"
    },
		"apriora": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 206,
        priv: "Полный привод",
        mass: "2.105 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lada Priora"
    },
		"ae86": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 274,
        priv: "Полный привод",
        mass: "2.160 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota AE86 DRIFT"
    },
		"agerars": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 355,
        priv: "Полный привод",
        mass: "1.540 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Koenigsegg Agera RS"
    },
		"a8audi": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Задний привод",
        mass: "1.521 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi A8"
    },
		"720s": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 245,
        priv: "Полный привод",
        mass: "2.150 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "McLaren 720s"
    },
		"922smg": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "2.190 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Porsche 911 2020"
    },
		"500w124": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "2.435 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz W124 AMG"
    },
		"675ltsp": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 300,
        priv: "Полный привод",
        mass: "1.870 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "McLaren 675 LTSP"
    },
		"2016rs7": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 200,
        priv: "Полный привод",
        mass: "2.435 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi RS7"
    },
		"challenger": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 246,
        priv: "Полный привод",
        mass: "2.275 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Dodge Charger"
    },
		"x5g05": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.350 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW X5 30D"
    },
		"x7bmw": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "2.555 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW X7"
    },
		"xc60": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 210,
        priv: "Полный привод",
        mass: "1.990 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Volvo XC60"
    },
		"z4bmw": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.610 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW Z4"
    },
		"rmodcamaro": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 316,
        priv: "Задний привод",
        mass: "1.761 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Chevrolet Camaro ZL1"
    },
	"lamboreventon": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 358,
        priv: "Полный привод",
        mass: "1.666 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Reventon"
    },
	    "Bmx": {
        desc: "",
        seats: 1,
        acceleration: 0.265,
        maxSpeed: 50,
        priv: "Задний привод",
        mass: "25 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMX"
    },
	"akuma": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 145,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Akuma"
    },
	"MGdddT": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 147,
        priv: "Задний привод",
        mass: "200 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ford Mustang 5.0"
    },
	"audiq7": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 119,
        priv: "Задний привод",
        mass: "220 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi Q7"
    },
	"f812": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 152,
        priv: "Задний привод",
        mass: "270 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ferrari F812"
    },
	"laferrari17": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 148,
        priv: "Задний привод",
        mass: "280 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "LaFerrar 2017"
    },
	"m52021": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 135,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M5F90 Restyling"
    },
	"rr14": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 118,
        priv: "Задний привод",
        mass: "220 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Range Rover Vogue"
    },
	"s3sedan": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 145,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi S3"
    },
	"w221s63": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 150,
        priv: "Задний привод",
        mass: "230 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz W221 AMG"
    },
	"bmwe34": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 90,
        priv: "Задний привод",
        mass: "100 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BWW E34"
    },
	"camryv55": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 140,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Camry V55"
    },
	"mcgts": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 140,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Porsche Macan GTS"
    },
	"mark2100": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 140,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Mark 2"
    },
	"tayotalc200": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 150,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Toyota Land Cruiser 200"
    },
	"lanxvp": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 130,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mitsubishi Lancer 10"
    },
	"bmwm4": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 120,
        priv: "Задний привод",
        mass: "600 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M4 Competition 2020"
    },
	"bmwx6m2020": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 142,
        priv: "Задний привод",
        mass: "220 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW X6M 2020"
    },
	"Cliffhanger": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 140,
        priv: "Задний привод",
        mass: "220 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Cliffhanger"
    },
	"skyline": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 142,
        priv: "Задний привод",
        mass: "205 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Nissan Skyline"
    },
	"Gargoyle": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 143,
        priv: "Задний привод",
        mass: "210 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Gargoyle"
    },
	"Ratbike": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 130,
        priv: "Задний привод",
        mass: "180 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ratbike"
    },
	"BF400": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 141,
        priv: "Задний привод",
        mass: "200 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BF400"
    },
	"verus": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 131,
        priv: "Задний привод",
        mass: "200 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Verus"
    },
	"Sanctus": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 144,
        priv: "Задний привод",
        mass: "250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Sanctus"
    },
	"Scorcher": {
        desc: "",
        seats: 1,
        acceleration: 0.265,
        maxSpeed: 55,
        priv: "Задний привод",
        mass: "40 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Scorcher"
    },
	"16charger": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 270,
        priv: "Задний привод",
        mass: "1.845 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Dodge Charger"
    },
"bentayga": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 200,
        priv: "Задний привод",
        mass: "1.960 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Bentley Bentayga"
    },
"lc300": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 345,
        priv: "Gjkysq привод",
        mass: "2.630 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Land Cruiser 300"
    },
	"can": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 345,
        priv: "Задний привод",
        mass: "1.730 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Donate Buggy"
    },
"sian": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 206,
        priv: "Задний привод",
        mass: "1.600 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Sian"
    },
	"ftype15": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "1.465 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Jaguar F-type"
    },
	"fastback": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 335,
        priv: "Задний привод",
        mass: "1.544 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ford Mustang Fastback"
    },
	"polp1": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 334,
        priv: "Задний привод",
        mass: "1.940 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "McLaren P1 Donater"
    },
	"serv_electricscooter": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 280,
        priv: "Полный привод",
        mass: "2.200 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Samokat"
    },
	"с63": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "2.360 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz C63 AMG"
    },
	"f8t": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 348,
        priv: "Задний привод",
        mass: "1.365 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Ferarri Tributo"
    },
	"senna": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 335,
        priv: "Задний привод",
        mass: "2.360 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "McLaren Senna"
    },
	"17m760i": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.755 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW 760i"
    },
	"19dbs": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 342,
        priv: "Задний привод",
        mass: "1.799 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Aston Martin DBS"
    },
	"rmodbugatti": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 314,
        priv: "Задний привод",
        mass: "1.530 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Bugatti La Voiture Noire"
    },
	"m6f06": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 324,
        priv: "Задний привод",
        mass: "1.739 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M6"
    },
	"panamera18": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 334,
        priv: "Задний привод",
        mass: "1.765 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Porsche Panamera Turbos"
    },
	"m4f82": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 350,
        priv: "Полный привод",
        mass: "1.575 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M4 F82"
    },
"lp610": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 325,
        priv: "Полный привод",
        mass: "1.422 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Huracan Coupe"
    },
"760m": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 330,
        priv: "Полный привод",
        mass: "1.810 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M760 Manhart"
    },
"s15mak": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 244,
        priv: "Задний привод",
        mass: "1.250 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Nissan Silvia"
    },
"ls430": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.840 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lexus LS430"
    },	
"2019m5": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 305,
        priv: "Полный привод",
        mass: "1.865 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M5f90 Competition"
    },
"rmodsianr": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 350,
        priv: "Полный привод",
        mass: "1.622 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Lamborghini Sian Roadster"
    },	
"s8d4": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 240,
        priv: "Задний привод",
        mass: "1.530 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi A8 Long"
    },
	"x6m": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 360,
        priv: "Задний привод",
        mass: "1.350 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW X6M"
    },
"rs62": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Передний привод",
        mass: "2.485 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi RS6"
    },	
"BMWM5CS": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Полный привод",
        mass: "1.851 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M5 CS"
    },	
"m5": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Передний привод",
        mass: "1.400 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M5 F10"
    },	
"rs7c8": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Передний привод",
        mass: "1.400 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Audi RS7 C8"
    },		
"s500": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Передний привод",
        mass: "1.851 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Mercedes-Benz W223"
    },		
"bmwx6m2020": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 220,
        priv: "Полный привод",
        mass: "1.851 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW X6M 2020"
    },		
"m3e92": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 250,
        priv: "Задний привод",
        mass: "1.655 кг.",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "BMW M3 E92"
    },
	
"boxville4": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 150,
        priv: "Полный привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "35000",
        vnut: "Да",
        rn: "Boxville"
    },
"e15082": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Полный привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "10000",
        vnut: "Да",
        rn: "Ford E-150 Van 1982"
    },	
"nspeedo": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Полный привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "75000",
        vnut: "Да",
        rn: "Vapid Speedo Express"
    },	
"mule3": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Полный привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "100000",
        vnut: "Да",
        rn: "Mule 3"
    },	
"mule4": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Полный привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "130000",
        vnut: "Да",
        rn: "Mule 4"
    },	
"pounder2": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Полный привод",
        mass: "2.000 кг.",
        vnet: "Нет",
        mat: "250000",
        vnut: "Да",
        rn: "Pounder"
    },	
"c63w205": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 290,
        priv: "Задний привод",
        mass: "1.655 кг.",
        vnet: "Нет",
        vnut: "Да",
		mat: "Нет",
        rn: "Mercedes-Benz AMG C63s"
    }, 
"sprinter211": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 180,
        priv: "Задний привод",
        mass: "2.140 кг.",
        vnet: "Нет",
        vnut: "Да",
		mat: "170000",
        rn: "Mercedes-Benz Sprinter"
    },
	"buzzard2": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Buzzard"
    },
	"frogger": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Frogger"
    },
	"frogger2": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Frogger 2"
    },
	"havok": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Havok"
    },
	"maverick": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Maverick"
    },
	"seasparrow": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Seasparrow"
    },
	"supervolito": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Supervolito"
    },
	"supervolito2": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Supervolito 2"
    },
	"swift": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Swift"
    },
	"swift2": {
        desc: "",
        seats: 000,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Swift 2"
    },
	"volatus": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Volatus"
    },
	"seasparrow2": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Seasparrow"
    },
	"microlight": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Microlight"
    },
	"howard": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 000,
        priv: "000",
        mass: "000",
        vnet: "Нет",
        mat: "Не вмещает",
        vnut: "Да",
        rn: "Howard"
    },
	"snowmobile": {
        desc: "",
        seats: 1,
        acceleration: 0.265,
        maxSpeed: 115,
        priv: "Полный привод",
        mass: "450 кг.",
        vnet: "Нет",
        vnut: "Да",
		mat: "Не вмещает",
        rn: "SnowMoto"
    },
	"alpinab7": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 329,
        priv: "Полный привод",
        mass: "2.070 кг.",
        vnet: "Нет",
        vnut: "Да",
		mat: "Не вмещает",
        rn: "BMW Alpina B7 2020"
    },
	"lp700dmc": {
        desc: "",
        seats: 2,
        acceleration: 0.265,
        maxSpeed: 350,
        priv: "Задний привод",
        mass: "1.575 кг.",
        vnet: "Нет",
        vnut: "Да",
		mat: "Не вмещает",
        rn: "Ferrari 812 N-largo"
    },
	"rs6m": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 320,
        priv: "Передний привод",
        mass: "2.100 кг.",
        vnet: "Нет",
        vnut: "Да",
		mat: "Не вмещает",
        rn: "Audi RS6 Mansory Sedan"
    },
	"xc90": {
        desc: "",
        seats: 4,
        acceleration: 0.265,
        maxSpeed: 220,
        priv: "Полный привод",
        mass: "1.939 кг.",
        vnet: "Нет",
        vnut: "Да",
		mat: "Не вмещает",
        rn: "Volvo XC90"
    },
};